name: euphoria
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  auto_route: ^3.2.4
  dartz: ^0.10.1
  uuid: ^3.0.6
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  get_it: ^7.2.0
  google_sign_in: ^5.3.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  google_fonts: ^2.3.2
  flutter_displaymode: ^0.4.0
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.0
  json_annotation: ^4.5.0
  freezed_annotation: ^1.1.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  cloud_firestore: ^3.1.13
  kt_dart: ^0.10.0
  salomon_bottom_bar: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  freezed: ^1.1.1
  change_app_package_name: ^1.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
